# Matrices and Statistics 

        This module reviews the basic matrix operaton and statistics concepts that are widely used in munipulating, processing, and describing data. The topics in the module may seem discrete and covers a variety of small topics. Students should have been exposed to these topics in high school and college math curiculum. However, you don't have to learn the math again to be data scientist. Python Numpy and Scipy libraries provide rich functions to automat many math operations. The key of this module is to understand the python APIs and when to use them.
        
        # Numpy (www.numpy.org)
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
tools for integrating C/C++ and Fortran code
useful linear algebra, Fourier transform, and random number capabilities
Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is licensed under the BSD license, enabling reuse with few restrictions. 
        
        
        # Numpy arrays and scalar
        Why do we need arrays while we have python lists
        1. efficent operation - smaller storage spaces
        2. Uniformed data type in array
        3. Vectorization for faster operatoin 
        
        The following is from user forum 
NumPy's arrays are more compact than Python lists -- a list of lists as you describe, in Python, would take at least 20 MB or so, while a NumPy 3D array with single-precision floats in the cells would fit in 4 MB. Access in reading and writing items is also faster with NumPy.

Maybe you don't care that much for just a million cells, but you definitely would for a billion cells -- neither approach would fit in a 32-bit architecture, but with 64-bit builds NumPy would get away with 4 GB or so, Python alone would need at least about 12 GB (lots of pointers which double in size) -- a much costlier piece of hardware!

The difference is mostly due to "indirectness" -- a Python list is an array of pointers to Python objects, at least 4 bytes per pointer plus 16 bytes for even the smallest Python object (4 for type pointer, 4 for reference count, 4 for value -- and the memory allocators rounds up to 16). A NumPy array is an array of uniform values -- single-precision numbers takes 4 bytes each, double-precision ones, 8 bytes. Less flexible, but you pay substantially for the flexibility of standard Python lists!
        
        

In [0]:
# Create and Index numpy arrays 

In [0]:
# Create an array
import numpy as np

a_array = np.array([1,3,5,7]) #create an array from list
a_list = [2,4,6,8]
a_array = np.array(a_list)    #convert existing list to array
b_list = [1,'bc','3',4]       
b_array = np.array(b_list)    #auto conversion to uniform type
c_list = [[1,2],3,{1:'4'}]    
c_array = np.array(c_list)    #works as list, but won't have computing functions

In [0]:
print(a_array)
print(b_array)
print(c_array)
print(type(c_array))
print(c_array.shape)
print(c_array[0])


[2 4 6 8]
['1' 'bc' '3' '4']
[[1, 2] 3 {1: '4'}]
<class 'numpy.ndarray'>
(3,)
[1, 2]


In [0]:
# Create special arrays using built-in functions
# empty, eye, identity, ones, zeros, full, arange 
# https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#from-existing-data 
print(np.empty([2,3,4])) # create 2x3x4 dimentional array without value signed  
print(np.zeros([2,3,4])) # create 2X3X4 dimentional array and assign 0 to all the 24 elements

print(np.eye(4,3))#Return a 2-D array with ones on the diagonal and zeros elsewhere.
                  #It's usually an NxN matrix for identity matrix
    
print(np.identity(4)) #another way to create identity matrix 

print(np.arange(50,20,-6.3))  #use arrange to create a loop structure list with init, end, and step 

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[ 50.   43.7  37.4  31.1  24.8]


In [0]:
# Multi-dimentional arrays

# Create the multi-dimentional list first
print(np.array([a_array,b_array]))  #conversion to to the same datatype 

# Create multi-dimnetional array from reshaping a one-dimnetional array
print(np.arange(24).reshape(2,3,4))

print(np.random.randn(24).reshape(2,3,4))



[['2' '4' '6' '8']
 ['1' 'bc' '3' '4']]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ -7.77060740e-01  -1.38009074e+00   1.45284733e+00   7.78311026e-02]
  [  7.46712492e-01   2.53943356e-01   1.25493715e+00  -1.13446496e-03]
  [  1.20515014e+00  -4.07350395e-01  -1.15876882e+00   2.01962500e-01]]

 [[  1.14589131e+00   8.68101270e-01   5.77819155e-01   8.47921825e-03]
  [ -3.11031567e-01   8.25312802e-01   2.56484017e-01  -2.35505364e-02]
  [ -2.72051329e-01   1.02450347e+00  -8.70192680e-01   1.76206143e+00]]]


# Scalar (not Vector)

    " The quantity is either a vector or a scalar. These two categories can be distinguished from one another by their distinct definitions: Scalars are quantities that are fully described by a magnitude (or numerical value) alone. Vectors are quantities that are fully described by both a magnitude and a direction. Vectors have magnitude and direction, scalars only have magnitude. By definition, speed is the scalar magnitude of a velocity vector. "
    
    The scalar here is a one-dimnetional array, a record in a database table. But in other language, vectors and scalars are interchangable. Here, I just want to specify the difference from the definition of these two terms. In data sicnece, a dataset contains multiple scalars (records) in the horizental direction (row direction). The number of rows are the number of records. 
    
    When we imported an n x m dimention array directly from a data file, it usually means that there are n records of m-dimentional scalar. When you operate on arrays, it's good practice to write the shape of the arrays out first. 

In [0]:
np.add(a_array,b_array)

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [0]:
# let's create two 2 x 3 arrays
a_array = np.array([[1,2,3],[4,5,6]])
b_array = 1/a_array

print(a_array)
print(a_array.shape)
print(b_array)
print(b_array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 1.          0.5         0.33333333]
 [ 0.25        0.2         0.16666667]]
(2, 3)


In [0]:
# It's like the numerical operations on numbers (integers, float numbers ...), we can use the 
# same set of operations on arrays. Another way to think it is that a number is 1 x 1 array. 

print(a_array*b_array)
print(np.multiply(a_array,b_array))

print(a_array/b_array)
print(np.divide(a_array,b_array))

print(a_array+b_array)
print(np.add(a_array,b_array))

print(a_array-b_array)
print(np.subtract(a_array,b_array))

print(a_array**2)
print(np.power(a_array,2))

print(a_array)




[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[  1.   4.   9.]
 [ 16.  25.  36.]]
[[  1.   4.   9.]
 [ 16.  25.  36.]]
[[ 2.          2.5         3.33333333]
 [ 4.25        5.2         6.16666667]]
[[ 2.          2.5         3.33333333]
 [ 4.25        5.2         6.16666667]]
[[ 0.          1.5         2.66666667]
 [ 3.75        4.8         5.83333333]]
[[ 0.          1.5         2.66666667]
 [ 3.75        4.8         5.83333333]]
[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]
21


In [0]:
# Find, calculate values within array
print(a_array)
print(np.max(a_array))
print(np.min(a_array))
print(np.average(a_array))
print(np.mean(a_array))
print(np.sum(a_array)) 

# only calculate along one direction by defining axis
print(np.min(a_array, axis=0))
print(np.mean(a_array,axis=0))
print(np.sum(a_array, axis=0))
print(np.sum(a_array, axis=1))





6
[1 2 3]
3.5
[ 2.5  3.5  4.5]
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


In [0]:
# Matrix multiplication 
# n x m * m x l => n x l
#np.dot(a_array,b_array)

a_array_T = a_array.T
print(a_array_T)
print(np.dot(a_array, a_array_T))   # 2x3 * 3x2 => 2x2
print(a_array.dot(a_array_T))       # both np.dot or array.dot work

[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


In [0]:
#slicing 
#similiar to Lists, slicing can be done on matrices by following the example
a_array=np.array([[1,2],[3,4],[5,6]])

In [0]:
a_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
print(a_array[1,0])
print(a_array[1][0])
print(a_array[:2,1:])

3
3
[[2]
 [4]]


In [0]:
# a little algebra
# get the inverse of a SQUARE matrix

#import linalg module from scipy library which is built on top of numpy
from scipy import linalg

# generate a random 3 x 3 squre array
a_array=np.random.rand(3,3)
print(a_array)
a_inv = linalg.inv(a_array)
print(a_inv)
print(a_array.dot(a_inv))


[[ 0.12258382  0.8918384   0.95888934]
 [ 0.15270563  0.83031949  0.40293717]
 [ 0.83324488  0.21232618  0.80811845]]
[[-1.57721899  1.3931373   1.17684687]
 [-0.5720604   1.88564881 -0.26141635]
 [ 1.77656263 -1.93189145  0.09268926]]
[[  1.00000000e+00   2.22044605e-16   1.38777878e-17]
 [  1.11022302e-16   1.00000000e+00   2.08166817e-17]
 [  4.44089210e-16  -2.22044605e-16   1.00000000e+00]]


In [0]:
# use inverse of a matrix to solve linear equation 
# http://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html 
# solve the equation a x = b for x =>  x = b/a = a to the power of -1 times b
# now, let's consider a and b are matrics (b is a scalar -> n by 1 matrix)
# Let's start from a simple one 5x = 10 --> x = 2
a = np.array([[5]])  #make sure a is a n by n square matrix [[]]
b = np.array([10])
x = linalg.inv(a).dot(b)
print(x)

# Let's solve a real problem 
'''
answer is 2,3, 0.5 

5 2.5 4   19.5
1.4 2 -1  8.3
12 -3 -6  12 

'''

a = np.array([[5, 2.5, 4], [1.4, 2, -1], [12, -3, -6]])
b = np.array([19.5, 8.3, 12])
x = linalg.inv(a).dot(b)
print(x)
print(a.dot(x)-b)  #verification: the result should be close to a scalar of zeros

#a faster and eaiers way to do it is to use .slove(a,b), but you have to 
# remember the exisitance the these functions
# the rule of thumb is that if they exist, use them, don't re-invent the wheels
x1 = np.linalg.solve(a,b)
print(x1)





[ 2.]
[ 2.   3.   0.5]
[ 0.  0.  0.]
[ 2.   3.   0.5]
